apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespaceOverride }}
type: Opaque
stringData:
   JENKINS_USER: {{.Values.jenkins.user | quote }}
   JENKINS_TOKEN: {{.Values.jenkins.token | quote }} 